apiVersion: v2
name: olivetin
description: A OliveTin Helm chart for Kubernetes
icon: https://www.olivetin.app/resources/images/logo.png
home: https://www.olivetin.app
sources:
  - https://github.com/OliveTin/OliveTin
maintainers:
  - name: OliveTin contributors
    url: https://github.com/OliveTin/OliveTin

type: application

version: 2.2.3

appVersion: "2025.4.8"

annotations:
  artifacthub.io/signKey: |
    fingerprint: 693815EF9D1E92A69EC8947EAB52AEAE08CE18DF
    url: https://www.olivetin.app/OliveTin-HelmChart/charts/pubkey.asc

keywords:
  - olivetin
  - shell
  - commands
