apiVersion: apps/v1
kind: Deployment
metadata:
    name: olivetin
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: olivetin
  template:
    metadata:
      labels:
        app: olivetin
    spec:
      containers:
        - name: olivetin
          image: docker.io/jamesread/olivetin:latest
          ports:
            - containerPort: {{ .Values.ingress.servicePort }}
          volumeMounts:
            - name: olivetin-config
              mountPath: "/config"
              readOnly: true

          livenessProbe:
            exec:
              command:
                - curl
                - localhost:{{ .Values.ingress.servicePort }}
            initialDelaySeconds: 5
            periodSeconds: 30

      volumes:
        - name: olivetin-config
          configMap:
            name: olivetin-config
