apiVersion: v1
kind: Service
metadata:
  name: olivetin
spec:
  ports:
  - port: {{ .Values.ingress.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.ingress.servicePort }}
  selector:
    app: olivetin
  type: ClusterIP
