apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "olivetin.fullname" . }}-config
  labels:
    {{- include "olivetin.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.olivetin.config.rawYaml | toYaml | nindent 4 }}
